baseURL = ''
languageCode = 'en-us'
title = 'Dhita Arsaid'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Arsaid"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Dhita Arsaid"
  icon = ""
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Dhita Arsaid"
  subtitle = "Hi there 👋 Welcome to my blog"
  imageUrl = "/images/profile.jpg"
  imageWidth = 170
  imageHeight = 170
  imageTitle = "my image"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/DhitaArsaid"

  [[params.socialIcons]]
  name = "RSS"
  url ="index.xml"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true


  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

  [outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Archives"
url = "archives/"
weight = 10

[[menu.main]]
name = "Posts"
url ="post/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 10

[markup.highlight]
noClasses = false
